version: 2

initWorkingDir: &initWorkingDir
  type: shell
  name: Initialize Working Directory
  pwd: /
  command: |
    mkdir -p ~/go/src/${CIRCLE_PROJECT_USERNAME}/metadata_edns0
    sudo chown -R circleci ~/go
    mkdir -p ~/go/out/tests
    mkdir -p ~/go/out/logs
    mkdir -p /home/circleci/logs
    GOROOT=$(go env GOROOT)
    sudo rm -r $(go env GOROOT)
    sudo mkdir $GOROOT
    LATEST=$(curl -s https://golang.org/VERSION?m=text)
    curl https://dl.google.com/go/${LATEST}.linux-amd64.tar.gz | sudo tar xz -C $GOROOT --strip-components=1

integrationDefaults: &integrationDefaults
  machine:
    image: ubuntu-1604:201903-01
  working_directory: ~/go/src/${CIRCLE_PROJECT_USERNAME}/metadata_edns0
  environment:
    - K8S_VERSION: v1.15.3
    - KUBECONFIG: /home/circleci/.kube/kind-config-kind
    - KIND_VERSION: v0.5.1

setupKubernetes: &setupKubernetes
  - run:
      name: Setup Kubernetes
      command: ~/go/src/${CIRCLE_PROJECT_USERNAME}/ci/build/kubernetes/k8s_setup.sh

buildMetadataEdns0Image: &buildMetadataEdns0Image
  - run:
      name: Build latest CoreDNS+metadata_edns0 Docker image
      command: |
        cd ~/go/src/${CIRCLE_PROJECT_USERNAME}/metadata_edns0
        GO111MODULE=on go get -v -d
        make coredns SYSTEM="GOOS=linux" && \
        mv ./coredns ../coredns/
        cd ../coredns/

        docker build -t coredns . && \
        kind load docker-image coredns

jobs:
  metadata_edns0-tests:
    <<: *integrationDefaults
    steps:
      - <<: *initWorkingDir
      - checkout
      - run:
          name: Get CI repo
          command : |
            mkdir -p ~/go/src/${CIRCLE_PROJECT_USERNAME}/ci
            git clone https://github.com/${CIRCLE_PROJECT_USERNAME}/ci ~/go/src/${CIRCLE_PROJECT_USERNAME}/ci
      - run:
          name: Clone CoreDNS repo
          command: |
            mkdir -p ~/go/src/${CIRCLE_PROJECT_USERNAME}/coredns
            git clone https://github.com/${CIRCLE_PROJECT_USERNAME}/coredns ~/go/src/${CIRCLE_PROJECT_USERNAME}/coredns
      - <<: *setupKubernetes
      - <<: *buildMetadataEdns0Image
      - run:
          name: Run metadata_edns0 plugin tests
          command: |
            cd ~/go/src/${CIRCLE_PROJECT_USERNAME}/ci/test/metadata_edns0
            GO111MODULE=on go test -v ./...

workflows:
  version: 2
  integration-tests:
    jobs:
      - metadata_edns0-tests
